### PR TITLE
chore(deps): include tslib

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/yaml/issues/36
Lodash was not used.

### CODE REVIEW

**Comment by marcelltoth** [comment]
We should probably check the other packages have the same problem. Unless explicitly overridden, all of our packages are compiled with `importHelpers: true`, so we should make sure tslib is referenced everywhere.

**Comment by marcelltoth** [comment]
Pinging @marbemac to double check that this is a possible issue in all of our repos, right?

**Comment by P0lip** [comment]
> Pinging @marbemac to double check that this is a possible issue in all of our repos, right?

Yes and no.
Some repose such as markdown or json use rollup, so they are not prone to this issue.
Although, there are some that in fact may lack the dependency, yet I'd say it's rather not too common, hopefully.

**Comment by P0lip** [comment]
I think JSE is one of the dependency that does rely on tslib, but doesn't have it listed, but it's a private component, and hence is not used in a plain JS project.
I'll add that dependency there later today though, as I'll need to update `@stoplight/json` package.

**Pull request merged**
