### PR TITLE
perf(parsing): reuse seenKeys array

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by wmhilton** [comment]
How much of a perf difference did this make?

**Comment by P0lip** [comment]
> How much of a perf difference did this make?

Didn't measure, should be rather negligible, but potentially saves a couple GC cycles

**Comment by wmhilton** [comment]
> Didn't measure, should be rather negligible

This hyper-optimization goes directly against the Chrome Team's advice of "write idiomatic JavaScript" though. I don't think we should introduce something this subtle unless we have evidence. Setting the `.length` property on an Array gives me the shivers. I know it's allowed but it feels _wrong_.

**Comment by P0lip** [comment]
> "write idiomatic JavaScript"

How is that not idiomatic? We just re-use the array, nothing else.


>  Setting the .length property on an Array gives me the shivers. I know it's allowed but it feels wrong.

It's actually pretty common. We can always do
```ts
while (foo.length > 0) foo.pop(); // or shift
```
or 
```ts
foo.splice(0, foo.length);
```

**Comment by P0lip** [comment]
Also, `const seenKeys: string[] = []` vs `const seenKeys = [''];` fewer chars :trollface:

**Comment by P0lip** [comment]
Screw it

**Pull request closed without merging**
